### ISSUE TITLE
i can migrate CAR links from old.web3.storage to w3up via store/add invocations

### ISSUE THREAD

**Issue by gobengo** [web3-storage/migrate-to-w3up#2]
```[tasklist]
### Tasks
- [x] add CAR links to uploads list API in old.web3.storage https://github.com/web3-storage/web3.storage/pull/2347
- [ ] https://github.com/web3-storage/migrate-to-w3up/pull/3/
- [ ] https://github.com/web3-storage/w3up/issues/1300
```

Nice to Haves (maybe after MVP):
* progress bar

**Comment by gobengo** [comment]
#status working prototype over here https://github.com/web3-storage/migrate-to-w3up/pull/3

**Comment by gobengo** [comment]
I merged #3 and will use other issues for further improvements to it.
